root = "."
tmp_dir = "bin"

[build]
pre_cmd = ["templ generate"]
cmd = "go build -o ./bin/galleria ./cmd/galleria"
bin = "bin/galleria"
include_ext = ["templ", "css", "js", "go"]
exclude_regex = ["_templ\\.go"]
